import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="w-full h-full">
      <body className="w-full h-full">
        <main className="flex items-center justify-center w-full h-full">{children}</main>
      </body>
    </html>
  );
}
